/**
 * VidSrc Hash Analysis v5
 * Fetch the base64.js and sbx.js files to understand hash generation
 * Also check if Turnstile appears intermittently
 */

const TMDB_ID = '1228246';
const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

async function fetchPage(url: string, referer?: string) {
  const headers: Record<string, string> = {
    'User-Agent': USER_AGENT,
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.9',
  };
  if (referer) headers['Referer'] = referer;
  const response = await fetch(url, { headers });
  return await response.text();
}

async function main() {
  console.log('='.repeat(80));
  console.log('VIDSRC HASH ANALYSIS v5 - SCRIPT ANALYSIS');
  console.log('='.repeat(80));

  // Fetch the base64.js and sbx.js files
  console.log('\n[1] Fetching cloudnestra scripts...');
  
  const base64Js = await fetchPage('https://cloudnestra.com/base64.js', 'https://cloudnestra.com/');
  await Bun.write('debug-cloudnestra-base64.js', base64Js);
  console.log(`base64.js length: ${base64Js.length}`);
  console.log(`base64.js preview:\n${base64Js.substring(0, 500)}`);
  
  const sbxJs = await fetchPage('https://cloudnestra.com/sbx.js?t=1751380596', 'https://cloudnestra.com/');
  await Bun.write('debug-cloudnestra-sbx.js', sbxJs);
  console.log(`\nsbx.js length: ${sbxJs.length}`);
  console.log(`sbx.js preview:\n${sbxJs.substring(0, 500)}`);
  
  // Check for Turnstile multiple times
  console.log('\n[2] Checking for Turnstile (10 requests)...');
  
  const embedUrl = `https://vidsrc-embed.ru/embed/movie/${TMDB_ID}`;
  let turnstileCount = 0;
  let noTurnstileCount = 0;
  
  for (let i = 0; i < 10; i++) {
    const embedHtml = await fetchPage(embedUrl);
    const rcpMatch = embedHtml.match(/cloudnestra\.com\/rcp\/([^"']+)/i);
    
    if (rcpMatch) {
      const rcpUrl = `https://cloudnestra.com/rcp/${rcpMatch[1]}`;
      const rcpHtml = await fetchPage(rcpUrl, embedUrl);
      
      const hasTurnstile = rcpHtml.includes('turnstile') || rcpHtml.includes('cf-turnstile');
      const hasProRcp = rcpHtml.includes('/prorcp/');
      
      if (hasTurnstile) {
        turnstileCount++;
        console.log(`  Request ${i + 1}: TURNSTILE detected`);
      } else if (hasProRcp) {
        noTurnstileCount++;
        console.log(`  Request ${i + 1}: No Turnstile, ProRCP available`);
      } else {
        console.log(`  Request ${i + 1}: Unknown state`);
      }
    }
    
    await new Promise(r => setTimeout(r, 300));
  }
  
  console.log(`\nResults: ${turnstileCount} with Turnstile, ${noTurnstileCount} without`);
  
  // Now let's look at the data-i attribute which might be important
  console.log('\n[3] Analyzing data-i attribute...');
  
  const embedHtml = await fetchPage(embedUrl);
  const rcpMatch = embedHtml.match(/cloudnestra\.com\/rcp\/([^"']+)/i);
  
  if (rcpMatch) {
    const rcpUrl = `https://cloudnestra.com/rcp/${rcpMatch[1]}`;
    const rcpHtml = await fetchPage(rcpUrl, embedUrl);
    
    // Extract data-i
    const dataIMatch = rcpHtml.match(/data-i="(\d+)"/);
    if (dataIMatch) {
      console.log(`data-i value: ${dataIMatch[1]}`);
      
      // This might be a movie/content ID
      // Let's see if it's related to TMDB ID
      console.log(`TMDB ID: ${TMDB_ID}`);
    }
    
    // Look for any other interesting data attributes
    const dataAttrs = rcpHtml.match(/data-[a-z]+="[^"]+"/gi) || [];
    console.log(`\nAll data attributes:`);
    dataAttrs.forEach(attr => console.log(`  ${attr}`));
  }
  
  // Let's try to understand the hash generation by looking at the embed page
  console.log('\n[4] Analyzing embed page for hash generation clues...');
  
  const embedHtml2 = await fetchPage(embedUrl);
  await Bun.write('debug-fnaf2-embed-v5.html', embedHtml2);
  
  // Look for any JavaScript that generates the RCP hash
  const scripts = embedHtml2.match(/<script[^>]*>([\s\S]*?)<\/script>/gi) || [];
  
  for (let i = 0; i < scripts.length; i++) {
    const script = scripts[i].replace(/<\/?script[^>]*>/gi, '').trim();
    if (script.length > 50 && script.length < 50000) {
      if (script.includes('rcp') || script.includes('cloudnestra') || script.includes('hash') || script.includes('md5')) {
        console.log(`\nScript ${i + 1} contains relevant keywords:`);
        console.log(script.substring(0, 1000));
      }
    }
  }
  
  // Check if the RCP hash is embedded directly in HTML or generated by JS
  const iframeMatch = embedHtml2.match(/<iframe[^>]*src=["']([^"']+)["'][^>]*>/i);
  if (iframeMatch) {
    console.log(`\nIframe found directly in HTML: YES`);
    console.log(`This means the RCP hash is generated SERVER-SIDE on vidsrc-embed.ru`);
  }
  
  console.log('\n' + '='.repeat(80));
  console.log('KEY INSIGHT');
  console.log('='.repeat(80));
  
  console.log(`
The flow is:
1. vidsrc-embed.ru generates RCP hash SERVER-SIDE
2. RCP page on cloudnestra.com generates ProRCP hash SERVER-SIDE
3. Both hashes contain encrypted data that changes every request

Since Turnstile is NOT appearing consistently, we might be able to:
1. Keep fetching until we get a response without Turnstile
2. Or there might be rate limiting that triggers Turnstile

Current status: ${noTurnstileCount > 0 ? 'ProRCP is accessible without Turnstile!' : 'Turnstile is blocking access'}
`);
}

main().catch(console.error);
