/**
 * VidSrc Hash Decoder - Deep Analysis
 */

import * as crypto from 'crypto';

const RCP_HASH_RAW = 'MzUwZGQyYjdhMzkxN2M4ZTU5NjE2NDA0Mzk4Y2NiZWU6ZEhsMmJXWmpURFpRVDFSVVYzQjBhR1JCTlhSV05IVkxZMlJVTlZOdlEwdEtNMWMzVjBVdllWbHlkbWRxZGtkb1dVTnVabVZzU0V0T1RsbHNkVTVGZEVOT2JWa3ZWMEZ4ZUZsRlduZHplbHB2WjIxWmN6RmxOSFJUUTI5WmNYbFllVlJTSzI5Q2RFNW1PRlZOYVV4WlNtZHZURzF6VG1Sc1ZUWlNRV1YxVVRWRloxbFpjRmRSZG1WSlJrRXdVRTlEYkU5d09YUTVkRUpRUlROeGVHTjBORlpQVm10S2IwaERlSFpxYWpKS1YwZHNhRmd2VEdaT1FVUjVObTl4TUZSUmNtSm9haTlsYldSUFpqQktVR05pY1RKUVlYWjJja2hpTlZKVFdHVkxhMVUzWjBKbFFuTjNhR1I0U3poSVZYbEdWeko0TUM5MWVsWXJNbHBRVmxGM2MyZHpjR1p0Y2s1T1lYaEJOMFJRV2tkdU4wRkljbmhXZVd4alJsUlVVWEk1VTJWRllWaHhOV2xTT0hGRVVGVTBiVlpJUm1OQ05rSmhjblYxYnpCSFRVbEVLMXBTVEVSM1ZUUlFXRzFxYTJsTGJrZERSRGx3WVZONFNsVm1ZMkUxV2tGd01TOVlSMVZVTVdsUk9VbHFVVVpJV0hwc1RURm5TaTk2UmpKYU5uazFlRkl2YWs1UEwxUldhMVJJVW05V1ZqTTFNQzltVmpadFUycEJkRmxRT0M5MGJYSkdPR0k0UnpWSGFXNVZTMVpXVWt0cU16Rm9iVGNyVlZVd1puTnFhVmhqVTNsRlVuSlZRVGhRT0ZWUGNXeEtPVmd3YjNSbWVUZHdNQzh4S3pWcFVGUndMMm8wZWtzMlUxWkZPWFJNUVVsREwyZDZRMjVKTlRKNFJraEdPU3R5YjA1SFMxWlhiRkZyTmpGQlpqUXdWMjltU1cxeVRESlBha1UxYVd3M1RrazBiV2w2Y1VGaWNqZHVObUU1VUhKMVoyMDRMMjg1ZWtOSVFUTXhUVU56YURkQlRXZEJaSHBPUnpOQmIxUktabmx6U2xoWVMxUkliek5YVEVOd1dWRjNXRko0Y0RaUlIyOVViRXMwZVRoWmMyaFhSRE5tV1dnMVVuaHJSMGR5U0djclVUUjFPRXRzYTBKU1JVdGtPSHBvTlVSelNqZHpaWGRQTWxFME1qWkJOVUpWWWxSTVRsSm1aWEl5VUV0alJ6ZHZlRE5hZGxrd1ZFcG5SeTlEVTNaU00xaG5kUzh4VFhwa2JrcG1WWFZ2WnpZNGMzQnFUVzVQWm5SR01WVTBkRmdySzNwSGQzWndZVkJKU0ZodFEzRnJLMVZST1c1UlpYVTFUaXRpUVV0WVRtTjFjWGhrV21NMGVuUkNlazVtV2pKM2VGbHhWMk4wVWtkYVMycGxlV2hCVEZKUFpXTlhSSFEwUjJocEwzUTJNMW8wSzFZelpUbHVXRU5GU0dsd1pWZGtkelJKYW0xTFdsVm5SSHBXVm1oVVZXSlhaSE5MVmtWclQzZG1WemRUTnpKTFJWTjBVa0ZVZGpsc1VXZENTRnBGV1hCSVMzQlRZazVyY0hvMk5WQk5ibmt2UVdkWFdtZ3pWSGRYUjA5QmFTdDBkVXRNTkcxNlVrUTNPV292ZVdsMU9FWXZOVFpZWlRKQ1RETmtja0ZTS3pOM2JVOW1NSFF2T1dKRVFUZG1PV3BwVDBvNFNsQllZbXRQUjBkU1VsZDFPRFU1TUVwVVdXOWthbTkzZW1oRWRuUXhjUzlNTVRSU1ZXUTVVRUZRYm1oa2NIbFJXR1ZCZVZKTE5FRnhVWFVyYkd3MllsVlFiRzlpVFdGMVpHdEZVV3QwZFVwWVFuWkNUVW95YjBGeVR6RmhMMDE1YWxWMWNHaFNOMFZxUjFoNlMweEpiUzl0TUN0VmNITmxlRk0zSzI1NE1tcFNXR1I2YXpGcFNUbHdUVUpMWWt0VFdEQkNORWxsVkhZeVJtMVNVMmxxZDB4alpXSk1iWFo2VGpaSlJVeEdMekZaSzBVM0x6ZGFXSFZWYmxnNE5raHJNVTlOVjBvcmNYUnJRMGhuUVc1NGRFWkVNR1poVkRRelZHazBlbGhpV1RCV2NYbG5kMjF2ZW1Nd1NVUlBVMWRWZFdSdmJGUnpaRTV6T1E9PQ--';

const PRORCP_HASH_RAW = 'MjAwODE2ODZiZTM1ZGQ4YWNhMjM5NTU2MGI3ZTQ4ZmU6T1dVd2VtMXZRMVUxUmprd05IbGxWalpaWkN0Tk9UWXlWM0paVVZKRGEwTTRNamc0YzNsU1JHaG5hSFZQVmpKeGNUZHhXbFJIZEV4c0t6RmxVbEJyU0hVclJ6aHZVa2hIVDNwMk1XUllXbEZsZWpjNFVDdFBjekpOWTNKVE5WVkxPV2RvTjAxck1uaGtlVzFOYjNkbkx5OXVZbVZWZEc5UVVuZFdUMGRoY25odlF5OVhibGhTT0hndlVGUnllRmRVVkVkRGQxSjNSRGhFVlZsc01uVjJTa0pXYldnNVRVZ3lZbkJRU25seFJIbFNPRTV4YWl0c2VtZzVZVVJ0V214M1FYQnNiek0wUjFScWFEbG9ZbE5RY1VGTmFXOUNTVlI1WVd3d1pXb3lNRU5DVTBrd1EwaHpaRVIyYm5aaGNVWmFiVkZVV0hWaFFuTXpibnBvTm5SdWExbEtUMFUwWVZGd1RXWlJlVUpzYVUxM1JWSk9aelZCY2pnNFRYbERSR1ZOV0ZOWVlqaGhjbk5hYkRKWlRtNWFTV0ZHWjNwUFduZ3ZPVU5XYzJWaVRGcDBXalpDTVRNMWVucEJjSE5CU2poS2FUWm9XVEF4V0VGblVFY3ZOVkprYm5ReGJTOHhibEJpV0ZZdldHVnNWU3QyY3pOcFdrNXhiRWRsVDJocU0xQlFkbGhqTUd0ME1sUm9MME0zZVhZMlNua3ZMMFI1UVhKV1dqQmFTblI1UjNGbGJXOHZlWGgwVG5ONlFVNXBXVGxTZUhNME1FSk9MMkV5TDJaNVdGQkhiMWt4VjFZMVZtVm5kRVZWVlVsWFRXWTJhV1kzU0Vvd0swRlFXa0o2TTFaUVIyWklaMEZxYVVoUFpuQnFXbEpPTVZoWVpWQnJRM2xsYURkSmVtNVZaRU01ZFdOa2NYb3ZObkF3UldoWFpHdG9XaXRxVGtscU1ERjZjM0k1WlhWUVlqSXJhRm96V214SFZWbFNSVVF3TmtscVkxUXZjREpGVmtNMUwxQk5RVXRtTWtFck4ySkRkbVpHZUZOSFRscElZVUUxYWxCV2FtMU1LM05PZVc5S05VOTBLMFJZTDNZMlZHeFhiemhRZWtWWGNHRnVTVmRWU21OU00yWnRNRlJ4Tm14R1IwVjBXRVJYVDNsNFQyRmtNMWxKV1M5MllVZFlNbWh2V0VwTVlXdEVTbVJEUjNReVVtbFhOa3BwZUhNNVFqaElUSFUyTDJNMmVteGlObmwzYWtscWJVeERTV041UkRNMFdFaGhOazUwT1V4dVVreFROemwxVWxRNVRtcDRhSEJSU1VoUFVscGpUMFJPZFVGeVYwdHRUalVyUW1WaVdXMXhNWFJ2Um01a1IzYzJRMGhoTVN0R1IwdEJiWEk0V0dOeVpVdEVVMHAwWjFaelpIRjNRMDVpY0ZCUWIweFpjMUpDYlZKalVXbFdVMkkyU0hCbFNsVkJlR3RaVUdodVJHVmFWVmRXZFd4d01XY3dUbTg0VWt0UWJHNDRNMlZwV0RJNVJsUlRTMFJhVDNscGQxUk1jRzAwUWxwcVIzZzFZa2RMTVROUGFtUmxiMkozTnpGbk5FSk9USE50YzB4ckwxbE5NRVJDYW5CeFNrWlVVbGhyZDFreWRVOVFiRVZFVVdoMlUyWjVRV1p4ZFRRMFNFcGpha0Z0YzBSdVlsUnRiMmhoY0VGa1dYVlZlVGRKY3k5VlRWZ3ZPRWxYTDNFd2JYaFNkVUZaZFRGa1ZWTkRkR1ZpYTBkMGJ6aDFVbVpGVEZKQlNESkVTVzluVGpBeVdrNW1lbWhaV25odWJYRkJja3hqVm1GSlRETklWMUpLYmpCRmNUaEpaVGRWTTFSWVNEbHRUV1ZQVmtKNVFrbG1aR3RDZFM5NldGVjJZMkZsV1N0RlIzSlJXR2M0YUVZdk1XWk1RMmhNY1VweFkwZHZSbE54V2t0cmQwMVpTR2d3VFVOclREQjJSMDVGV25wcVJHVkVUMDFZT0ZvemFFRkpSa2hVUVVaQ1NFd3dOMVJVYTBaWGFTc3ZhVWczYkhNM2RXaHZXSEZHTWl0VFZtRkliRlZ6ZVhWWGExZE1Ra0puTkdaT2RFNHlkMDlsVEd4dVMwVkphbEZwVm5WUmVHRXZNRTR5TTI5cGVHRjVia1ZLTWc9PQ--';

function b64(str: string): string {
  let n = str.replace(/--$/, '').replace(/-/g, '+').replace(/_/g, '/');
  while (n.length % 4 !== 0) n += '=';
  return Buffer.from(n, 'base64').toString('utf-8');
}

console.log('='.repeat(80));
console.log('VIDSRC HASH DEEP ANALYSIS');
console.log('='.repeat(80));

// Decode RCP
console.log('\n[1] RCP HASH');
const rcpDecoded = b64(RCP_HASH_RAW);
const [rcpMd5, rcpData] = rcpDecoded.split(':');
console.log('MD5:', rcpMd5);
console.log('Data preview:', rcpData.substring(0, 80));

const rcpInner = b64(rcpData);
console.log('Inner decoded:', rcpInner.substring(0, 150));

// Decode ProRCP
console.log('\n[2] PRORCP HASH');
const prorcpDecoded = b64(PRORCP_HASH_RAW);
const [prorcpMd5, prorcpData] = prorcpDecoded.split(':');
console.log('MD5:', prorcpMd5);
console.log('Data preview:', prorcpData.substring(0, 80));

const prorcpInner = b64(prorcpData);
console.log('Inner decoded:', prorcpInner.substring(0, 150));

// Compare
console.log('\n[3] COMPARISON');
console.log('RCP Inner length:', rcpInner.length);
console.log('ProRCP Inner length:', prorcpInner.length);
console.log('Same?', rcpInner === prorcpInner);

// Try 3rd level decode
console.log('\n[4] 3RD LEVEL DECODE');
try {
  const rcp3 = b64(rcpInner);
  console.log('RCP 3rd:', rcp3.substring(0, 150));
} catch { console.log('RCP 3rd: FAILED'); }

try {
  const prorcp3 = b64(prorcpInner);
  console.log('ProRCP 3rd:', prorcp3.substring(0, 150));
} catch { console.log('ProRCP 3rd: FAILED'); }

// MD5 tests
console.log('\n[5] MD5 TESTS');
const tests = ['1228246', 'movie/1228246', prorcpData, rcpData, prorcpInner, rcpInner];
for (const t of tests) {
  const h = crypto.createHash('md5').update(t).digest('hex');
  const match = h === rcpMd5 ? ' <-- RCP!' : h === prorcpMd5 ? ' <-- PRORCP!' : '';
  console.log(`MD5("${t.substring(0,30)}...") = ${h}${match}`);
}

console.log('\nDone.');
